def get_prompts_piano(num=50):
    NEUTRAL_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "an upbeat song",
        "a slow song",
        "a fast-paced track",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "aggressive music",
        "gentle music",
        "powerful music",
        "soft music",
        "loud music",
        "rhythmic music",
        "harmonious music",
        "dissonant music",
        "simple music",
        "complex music",
        "minimalist music",
    ]
    POSITIVE_PROMPTS = [f"{p} with piano" for p in NEUTRAL_PROMPTS]
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_mood(num=50):
    BASE_PROMPTS = [
        "song",
        "melody",
        "music",
        "tune",
        "track",
        "composition",
        "instrumental music",
        "piece of music",
        "background music",
        "musical performance",
        "pop song",
        "rock song",
        "jazz piece",
        "classical piece",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "ballad",
        "love song",
        "piano music",
        "guitar music",
        "synth music",
        "soundtrack",
        "cinematic music",
        "romantic music",
        "nostalgic music",
        "dreamy music",
        "intense music",
        "soulful music",
        "groovy music",
        "funky music",
        "smooth music",
        "raw music",
        "emotional music",
        "expressive music",
        "duet",
        "solo performance",
        "cover song",
        "original song",
        "remix",
    ]
    POSITIVE_PROMPTS = [f"a happy {p}" for p in BASE_PROMPTS]  # or "cheerful", "joyful"
    NEUTRAL_PROMPTS = [f"a sad {p}" for p in BASE_PROMPTS]  # or "melancholic", "somber"
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_tempo(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "piano music",
        "guitar music",
        "synth music",
        "a soundtrack",
        "cinematic music",
        "happy music",
        "sad music",
        "emotional music",
        "dramatic music",
        "intense music",
        "gentle music",
        "powerful music",
        "soft music",
        "groovy music",
        "funky music",
        "smooth music",
        "a duet",
        "a solo performance",
        "a cover song",
        "an original song",
        "a remix",
    ]
    POSITIVE_PROMPTS = [f"fast {p}" for p in BASE_PROMPTS]  # or "uptempo", "quick"
    NEUTRAL_PROMPTS = [f"slow {p}" for p in BASE_PROMPTS]  # or "downtempo", "leisurely"
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_female_vocals(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "a piece of music",
        "a musical performance",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "gentle music",
        "powerful music",
        "soft music",
        "an R&B song",
        "a soul song",
        "an indie song",
        "a disco song",
        "a funk song",
        "a gospel song",
        "an opera piece",
        "a lullaby",
        "a duet",
        "a cover song",
        "an original song",
        "a karaoke track",
        "a vocal performance",
    ]
    POSITIVE_PROMPTS = [f"{p} with female vocals" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"{p} with male vocals" for p in BASE_PROMPTS]
    LYRICS = """"""  # empty to allow vocals
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


def get_prompts_drums(num=50):
    BASE_PROMPTS = [
        "a song",
        "a melody",
        "music",
        "a tune",
        "a track",
        "a composition",
        "instrumental music",
        "a piece of music",
        "background music",
        "a musical performance",
        "a pop song",
        "a rock song",
        "a jazz piece",
        "a classical piece",
        "electronic music",
        "acoustic music",
        "orchestral music",
        "hip hop music",
        "country music",
        "blues music",
        "folk music",
        "reggae music",
        "metal music",
        "punk rock",
        "dance music",
        "ambient music",
        "lofi music",
        "a ballad",
        "a love song",
        "a happy song",
        "a sad song",
        "energetic music",
        "calm music",
        "dramatic music",
        "cheerful music",
        "melancholic music",
        "aggressive music",
        "gentle music",
        "powerful music",
        "soft music",
        "loud music",
        "rhythmic music",
        "harmonious music",
        "simple music",
        "complex music",
        "minimalist music",
        "funky music",
        "groovy music",
        "cinematic music",
        "a soundtrack",
    ]
    POSITIVE_PROMPTS = [f"{p} with drums" for p in BASE_PROMPTS]
    NEUTRAL_PROMPTS = [f"{p}" for p in BASE_PROMPTS]
    LYRICS = """[inst]"""
    return NEUTRAL_PROMPTS, POSITIVE_PROMPTS, LYRICS


CONCEPT_TO_PROMPTS = {
    "piano": get_prompts_piano,
    "mood": get_prompts_mood,
    "tempo": get_prompts_tempo,
    "female_vocals": get_prompts_female_vocals,
    "drums": get_prompts_drums,
}
